# Generated by Django 3.1 on 2020-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcontents',
            name='vpnPersistence',
            field=models.BooleanField(default=False, verbose_name='VPN profile persists through server upgrades'),
        ),
    ]
